### ISSUE TITLE
Add line numbers to lines

### ISSUE THREAD

**Issue by nirajacharyaa** [nirajacharyaa/JSONformatter#1]
`Note:` It shouldn't be hardcoded but be generated automatically for every line.
Number each line like this. 
![image](https://user-images.githubusercontent.com/54741119/193635209-2c3e6d95-8e8a-4350-aebd-a8f1ae8bd04b.png)

**Comment by metal-oopa** [comment]
Hi @nirajacharyaa 
You can check out my PR https://github.com/nirajacharyaa/JSONformatter/pull/3

It solves this issue.
