### ISSUE TITLE
Enhance the theme.

### ISSUE THREAD

**Issue by nirajacharyaa** [nirajacharyaa/JSONformatter#2]
Add dark and light mode features, also be free to refactor the HTML CSS in any way.

**Comment by deepesh16b** [comment]
Please assign this to me

**Comment by nirajacharyaa** [comment]
You can proceed. Best of luck.

**Comment by nirajacharyaa** [comment]
@deepesh16b Keep contributing, Happy Hacktoberfest. Don't forget to star the repo 😉
